export const data = [
	{
		id: 1,
		title: "GIT Web",
		subtitle: "Proyecto del sitio actual hecho con React + NextJs + Styled Components",
		imgUrl: "/img/pofo-thumbs/gitweb.jpg",
		linkUrl: "",
		tags: [],
	},
	{
		id: 2,
		title: "React Ecommerce Site",
		subtitle: "Ecommerce hecho con React/Redux, Firebase y Stripe API",
		imgUrl: "/img/pofo-thumbs/ecommerce.jpg",
		linkUrl: "",
		tags: [],
	},
	{
		id: 3,
		title: "Mech Keyboards",
		subtitle: "Teclados mecánicos animados hechos con HTML/CSS/JS vanilla",
		imgUrl: "/img/pofo-thumbs/keyboard.jpg",
		linkUrl: "",
		tags: [],
	},
	{
		id: 4,
		title: "Delilah Restó",
		subtitle: "Backend para App de comidas hecho con Node, Express y MySQL",
		imgUrl: "/img/pofo-thumbs/delilah.jpg",
		linkUrl: "",
		tags: [],
	},
	{
		id: 5,
		title: "gifOS",
		subtitle: "Página de GIFs que integra Giphy REST API como servicio de búsqueda y carga de gifs",
		imgUrl: "/img/pofo-thumbs/gifos.jpg",
		linkUrl: "",
		tags: [],
	},
	{
		id: 6,
		title: "React Testing Setup",
		subtitle:
			"Repositorio de ejemplo para workshop inicial orientado a testing en frontend utilizando React + Jest + Puppeteer + React Testing Library",
		imgUrl: "/img/pofo-thumbs/cra.jpg",
		linkUrl: "",
		tags: [],
	},
	{
		id: 7,
		imgUrl: "/img/pofo-thumbs/hoytrasnoche.jpg",
		title: "Hoy Trasnoche",
		subtitle: "Landing institucional para el podcast de cine 'Hoy Trasnoche' hecho con HTML/CSS vanilla",
		tags: [],
		linkUrl: "",
	},
	{
		id: 8,
		title: "Node Batch File Generator",
		subtitle:
			"Proyecto hecho en NodeJs + CSV Parser + jsDOM para realizar generación en serie de archivos en base a un archivo template base y una base de datos provista en CSV",
		imgUrl: "/img/pofo-thumbs/node.jpg",
		linkUrl: "",
		tags: [],
	},
	{
		id: 9,
		title: "Sitio Institucional Equals",
		subtitle: "Sitio corporativo hecho para empresa 'Equals'",
		imgUrl: "/img/pofo-thumbs/equals.jpg",
		linkUrl: "",
		tags: [],
	},
];
