export interface IPortfolioItems {
	id: number;
	title: string;
	subtitle: string;
	imgUrl: string;
	linkUrl: string;
	tags: Array<string>;
}

export const data: Array<IPortfolioItems> = [
	{
		id: 1,
		title: "GIT Web",
		subtitle: "Proyecto del sitio actual hecho con React + NextJs + Styled Components",
		imgUrl: "/img/pofo-thumbs/gitweb.jpg",
		linkUrl: "https://github.com/guido732/gitweb-next/",
		tags: ["javascript", "js", "react", "nextjs", "next", "styled components", "hooks", "functional components"],
	},
	{
		id: 2,
		title: "React Ecommerce Site",
		subtitle: "Ecommerce hecho con React/Redux, Firebase y Stripe API",
		imgUrl: "/img/pofo-thumbs/ecommerce.jpg",
		linkUrl: "https://github.com/guido732/ecommerce-site/",
		tags: [
			"javascript",
			"js",
			"react",
			"hooks",
			"redux",
			"sagas",
			"reselect",
			"css",
			"scss",
			"sass",
			"firebase",
			"firestore",
			"heroku",
			"stripe",
			"stripe api",
			"react stripe",
			"styled components",
			"node",
			"nodejs",
			"express",
			"functional components",
		],
	},
	{
		id: 3,
		title: "Mech Keyboards",
		subtitle: "Teclados mecánicos animados hechos con HTML/CSS/JS vanilla",
		imgUrl: "/img/pofo-thumbs/keyboard.jpg",
		linkUrl: "https://github.com/guido732/mechanical-keyboard/",
		tags: ["html", "vanilla", "js", "javascript", "css", "scss", "sass"],
	},
	{
		id: 4,
		title: "Delilah Restó",
		subtitle: "Backend para App de comidas hecho con Node, Express y MySQL",
		imgUrl: "/img/pofo-thumbs/delilah.jpg",
		linkUrl: "https://github.com/guido732/delilah-resto/",
		tags: [
			"node",
			"nodejs",
			"express",
			"sequelize",
			"mysql",
			"sql",
			"jwt",
			"token",
			"jason web token",
			"swagger",
			"open api",
			"postman",
		],
	},
	{
		id: 5,
		title: "gifOS",
		subtitle: "Página de GIFs que integra Giphy REST API como servicio de búsqueda y carga de gifs",
		imgUrl: "/img/pofo-thumbs/gifos.jpg",
		linkUrl: "https://github.com/guido732/gifOS/",
		tags: ["js", "javascript", "vanilla", "html", "scss", "sass", "css", "giphy", "api", "rest api"],
	},
	{
		id: 6,
		title: "React Testing Setup",
		subtitle:
			"Repositorio de ejemplo para workshop inicial orientado a testing en frontend utilizando React + Jest + Puppeteer + React Testing Library",
		imgUrl: "/img/pofo-thumbs/cra.jpg",
		linkUrl: "https://github.com/guido732/cra-testing-setup/",
		tags: [
			"javascript",
			"js",
			"react",
			"testing",
			"cra",
			"create react app",
			"jest",
			"puppeteer",
			"e2e",
			"unit test",
			"jest runner groups",
			"rtl",
			"react testing library",
		],
	},
	{
		id: 7,
		title: "Hoy Trasnoche",
		subtitle: "Landing institucional para el podcast de cine 'Hoy Trasnoche' hecho con HTML/CSS vanilla",
		imgUrl: "/img/pofo-thumbs/hoytrasnoche.jpg",
		linkUrl: "https://github.com/guido732/hoytrasnoche/",
		tags: ["landing", "html", "css", "sass", "scss", "semantic", "vanilla", "responsive", "mobile first"],
	},
	{
		id: 8,
		title: "Node Batch File Generator",
		subtitle:
			"Proyecto hecho en NodeJs + CSV Parser + jsDOM para realizar generación en serie de archivos en base a un archivo template base y una base de datos provista en CSV",
		imgUrl: "/img/pofo-thumbs/node.jpg",
		linkUrl: "https://github.com/guido732/auto-template-edit/",
		tags: ["node", "nodejs", "script", "nodejs", "csv", "jsdom", "dom"],
	},
	{
		id: 9,
		title: "Sitio Institucional Equals",
		subtitle: "Sitio corporativo hecho para empresa 'Equals'",
		imgUrl: "/img/pofo-thumbs/equals.jpg",
		linkUrl: "https://github.com/guido732/equals/",
		tags: ["landing", "html", "css", "sass", "scss", "semantic", "vanilla", "responsive", "mobile first", "bootstrap"],
	},
];
